"""Run discovery in a bidslake catalog (built with `bidslake index --adapter feat`).

The catalog is the source of truth for which files belong to which run: one
sibling-resolving query returns every MELODIC run with all of its per-run
inputs, the fix4melview classification files come back grouped per run, and
the motion parameters and per-component variance stats are read from the
catalog's ``feat_motion``/``feat_icstats`` tables rather than re-parsed from
the files. Callers get back local paths and arrays
(:class:`melodic.RunInputs`); a role that resolves to anything other than
exactly one file is reported as a problem, never guessed at.

The typed table models come from ``_lake_models``, generated by
``bidslake.stubgen`` from a feat-adapter catalog (``pixi run regen-lake-models
<catalog>``): the bundled ``bidslake.schema.models`` is pinned to the base BIDS
vocabulary and knows neither the feat overlay's suffixes nor ``feat_motion``.
"""

from __future__ import annotations

import dataclasses
import os
from collections.abc import Mapping, Sequence
from pathlib import Path
from typing import Any

import bidslake
import numpy as np
from sqlalchemy import ColumnElement, FromClause, select, true

from melrater.core import melodic
from melrater.core._lake_models import AllFiles, FeatIcstats, FeatMotion

#: Columns that identify one run. `dataset_id` keeps sibling matching inside
#: the anchor's own dataset — subject labels are only unique within one.
UNIT = ("dataset_id", "sub", "ses", "task", "run")

#: Sibling filters per input, from the feat adapter's vocabulary. Extensionless
#: matrix files pin `extension` to NULL so a stray `melodic_mix.bak` never pairs.
#: The motion and icstats roles resolve their files only for the table key
#: (file_id): the contents come from feat_motion/feat_icstats, not the paths.
_ROLES: dict[str, dict[str, str | None]] = {
    "bold": {"suffix": "bold", "desc": "filtered", "extension": ".nii.gz"},
    "ftmix": {"suffix": "spectrum", "desc": "MELODIC", "extension": None},
    "icstats": {"suffix": "metrics", "desc": "MELODIC", "extension": None},
    "features": {"suffix": "metrics", "desc": "fix", "extension": ".csv"},
    "ic": {"suffix": "components", "desc": "IC", "extension": ".nii.gz"},
    "mean": {"suffix": "boldref", "desc": "mean", "extension": ".nii.gz"},
    "mask": {"suffix": "mask", "desc": "brain", "extension": ".nii.gz"},
    "motion": {"suffix": "timeseries", "desc": "motion", "extension": ".par"},
}

_MOTION_COLUMNS = ("rot_x", "rot_y", "rot_z", "trans_x", "trans_y", "trans_z")

#: The required pair only: melrater consumes explained/total variance, and the
#: optional signal-change columns are legitimately NULL in two-column ICstats
#: files — fetching them would make a healthy run look gap-ridden.
_ICSTATS_COLUMNS = ("explained_variance", "total_variance")


@dataclasses.dataclass(frozen=True)
class DiscoveredRun:
    """One run the catalog knows about, ready to ingest — or not.

    ``inputs`` is None when the run cannot be ingested; ``problems`` says why
    (a role that matched nothing or was ambiguous, motion rows missing or
    unreadable). A gap is data, not an exception: the caller reports it and
    moves on to the next run.
    """

    label: str
    root: Path
    inputs: melodic.RunInputs | None
    problems: tuple[str, ...] = ()


def open_catalog(
    catalog: str | Path, *, base_dir: str | os.PathLike[str] | None = None
) -> bidslake.BidsLake:
    """Open the catalog read-only; ``base_dir`` rebases moved dataset roots."""
    return bidslake.open(str(catalog), base_dir=base_dir)


def discover_runs(
    lake: bidslake.BidsLake,
    *,
    sub: str | None = None,
    ses: str | None = None,
    task: str | None = None,
    run: str | None = None,
) -> list[DiscoveredRun]:
    """Every MELODIC run in the catalog matching the entity filters.

    Anchored on the mixing matrix (one per run) with every other input resolved
    as a sibling in the same query; classifications, motion rows, and ICstats
    rows follow in one query each, so a whole catalog costs four round-trips.
    """
    filters = {
        k: v
        for k, v in {"sub": sub, "ses": ses, "task": task, "run": run}.items()
        if v is not None
    }
    rows = _unit_rows(lake, filters)
    classifications = _classifications_by_unit(lake, filters)
    motion = _rows_by_file_id(
        lake,
        FeatMotion.__table__,
        _MOTION_COLUMNS,
        [fid for row in rows if (fid := _role_file_id(row, "motion")) is not None],
    )
    icstats = _rows_by_file_id(
        lake,
        FeatIcstats.__table__,
        _ICSTATS_COLUMNS,
        [fid for row in rows if (fid := _role_file_id(row, "icstats")) is not None],
    )

    out: list[DiscoveredRun] = []
    for row in rows:
        roles = {
            name: (
                bidslake.to_local_path(bidslake.sibling_path(lake, row, name))
                if row[f"{name}__n"] == 1
                else None
            )
            for name in _ROLES
        }
        fid = _role_file_id(row, "motion")
        sid = _role_file_id(row, "icstats")
        out.append(
            _assemble(
                anchor_path=row["file_path"],
                anchor_local=bidslake.to_local_path(bidslake.sibling_path(lake, row)),
                roles=roles,
                unresolved=bidslake.unresolved(row, _ROLES),
                classifications=classifications.get(_unit_key(row), ()),
                motion=motion.get(fid) if fid is not None else None,
                icstats=icstats.get(sid) if sid is not None else None,
            )
        )
    return sorted(out, key=lambda r: r.label)


def run_montage_paths(root: Path) -> tuple[Path, Path, Path]:
    """(melodic_IC, mean, mask) under an ingested run's directory.

    For re-rendering montages of a run that is already in the database: the
    feat layout names the slots, so the relative paths live in one place.
    """
    at = bidslake.layout("feat").under(root)
    return at["melodic_ic"], at["melodic_mean"], at["mask"]


def _unit_rows(
    lake: bidslake.BidsLake, filters: Mapping[str, str]
) -> list[dict[str, Any]]:
    a = AllFiles.__table__.alias("a")
    conds = [a.c.suffix == "mixing", a.c.desc == "MELODIC"]
    conds += [a.c[k] == v for k, v in filters.items()]
    cols: list[ColumnElement[Any]] = [a.c[k] for k in UNIT]
    cols += [a.c.root_uri, a.c.file_path]
    frm: Any = a
    for name, where in _ROLES.items():
        lat, sel = bidslake.sibling(a, name, UNIT, where)
        cols += sel
        frm = frm.outerjoin(lat, true())
    stmt = select(*cols).select_from(frm).where(*conds)
    return list(lake.sql(stmt).iter_rows(named=True))


def _classifications_by_unit(
    lake: bidslake.BidsLake, filters: Mapping[str, str]
) -> dict[tuple[str | None, ...], tuple[Path, ...]]:
    """Unit key -> local fix4melview paths (desc-auto only, i.e. FIX's own)."""
    c = AllFiles.__table__.alias("c")
    conds = [c.c.suffix == "classification", c.c.desc == "auto"]
    conds += [c.c[k] == v for k, v in filters.items()]
    cols = [c.c[k] for k in UNIT] + [c.c.root_uri, c.c.file_path]
    grouped: dict[tuple[str | None, ...], list[Path]] = {}
    for row in lake.sql(select(*cols).where(*conds)).iter_rows(named=True):
        local = bidslake.to_local_path(bidslake.sibling_path(lake, row))
        grouped.setdefault(_unit_key(row), []).append(local)
    return {key: tuple(paths) for key, paths in grouped.items()}


def _rows_by_file_id(
    lake: bidslake.BidsLake,
    table: FromClause,
    columns: Sequence[str],
    file_ids: Sequence[str],
) -> dict[str, np.ndarray]:
    """file_id -> (n_rows, len(columns)) from a row-ordered ingested table.

    A malformed source line is a NULL row in the table (holding its ordinal);
    it comes back as NaN here and `_assemble` reports it.
    """
    if not file_ids:
        return {}
    m = table.alias("m")
    stmt = (
        select(m.c.file_id, *[m.c[k] for k in columns])
        .where(m.c.file_id.in_(list(file_ids)))
        .order_by(m.c.file_id, m.c.row_idx)
    )
    return {
        key[0]: frame.select(columns).to_numpy()
        for key, frame in lake.sql(stmt).partition_by(["file_id"], as_dict=True).items()
    }


def _unit_key(row: Mapping[str, Any]) -> tuple[str | None, ...]:
    return tuple(row[k] for k in UNIT)


def _role_file_id(row: Mapping[str, Any], name: str) -> str | None:
    if row[f"{name}__n"] != 1:
        return None
    return bidslake.file_id(
        row[f"{name}__dataset_id"], row[f"{name}__root_uri"], row[f"{name}__file_path"]
    )


def _assemble(
    *,
    anchor_path: str,
    anchor_local: Path,
    roles: Mapping[str, Path | None],
    unresolved: Mapping[str, int],
    classifications: Sequence[Path],
    motion: np.ndarray | None,
    icstats: np.ndarray | None,
) -> DiscoveredRun:
    """Pure assembly of one row's resolutions into a DiscoveredRun."""
    # the anchor is <run dir>/filtered_func_data.ica/melodic_mix
    label = anchor_path.split("/", 1)[0]
    root = anchor_local.parents[1]
    problems = [
        f"{name} matched nothing" if n == 0 else f"{name} was ambiguous ({n} matches)"
        for name, n in sorted(unresolved.items())
    ]
    for table, name, data in (
        ("feat_motion", "motion", motion),
        ("feat_icstats", "icstats", icstats),
    ):
        # a resolved file with no table rows means the catalog never read it
        # (e.g. indexed by a bidslake without that table); an unresolved role
        # is already reported above
        if data is None:
            if name not in unresolved:
                problems.append(f"{table} has no rows for the {name} file")
        else:
            gaps = int(np.isnan(data).any(axis=1).sum())
            if gaps:
                problems.append(f"{table} has {gaps} unreadable row(s)")
    resolved = {name: path for name, path in roles.items() if path is not None}
    if problems or motion is None or icstats is None:
        return DiscoveredRun(
            label=label, root=root, inputs=None, problems=tuple(problems)
        )
    inputs = melodic.RunInputs(
        root=root,
        label=label,
        bold=resolved["bold"],
        mix=anchor_local,
        ftmix=resolved["ftmix"],
        features=resolved["features"],
        ic=resolved["ic"],
        mean=resolved["mean"],
        mask=resolved["mask"],
        classifications=tuple(classifications),
        motion=motion,
        icstats=icstats,
    )
    return DiscoveredRun(label=label, root=root, inputs=inputs)
