# Generated by Django 6.1 on 2026-08-29 13:59

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = (migrations.swappable_dependency(settings.AUTH_USER_MODEL),)

    operations = (
        migrations.CreateModel(
            name="Reviewer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("human", "Human"), ("fix", "FIX")], max_length=10
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("fix_model", models.CharField(blank=True, max_length=100)),
                ("fix_threshold", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reviewer",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Run",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("path", models.CharField(max_length=500)),
                ("label", models.CharField(max_length=200)),
                ("sub", models.CharField(blank=True, default="", max_length=100)),
                ("ses", models.CharField(blank=True, default="", max_length=100)),
                ("task", models.CharField(blank=True, default="", max_length=100)),
                ("run", models.CharField(blank=True, default="", max_length=100)),
                ("tr", models.FloatField(help_text="Repetition time (s)")),
                ("n_timepoints", models.PositiveIntegerField()),
                (
                    "fd",
                    models.JSONField(
                        help_text="Framewise displacement per volume (mm)"
                    ),
                ),
                (
                    "frequencies",
                    models.JSONField(help_text="Power-spectrum frequency axis (Hz)"),
                ),
                (
                    "metric_stats",
                    models.JSONField(
                        help_text="Per-metric distribution stats across this run's components"
                    ),
                ),
                (
                    "montage_format",
                    models.CharField(
                        default="avif",
                        help_text="File extension of rendered montages",
                        max_length=8,
                    ),
                ),
                (
                    "montage_digest",
                    models.CharField(blank=True, default="", max_length=16),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["label"], name="core_run_label_d66f73_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="Component",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("index", models.PositiveIntegerField(help_text="1-based IC number")),
                ("explained_var", models.FloatField()),
                ("total_var", models.FloatField()),
                ("timecourse", models.JSONField()),
                ("spectrum", models.JSONField()),
                (
                    "metrics",
                    models.JSONField(
                        help_text="Per-metric raw value and robust z-score"
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="components",
                        to="core.run",
                    ),
                ),
            ],
            options={
                "ordering": ["run", "index"],
            },
        ),
        migrations.CreateModel(
            name="Classification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        choices=[
                            ("Signal", "Signal"),
                            ("Noise", "Noise"),
                            ("Unknown", "Unknown"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "probability",
                    models.FloatField(
                        blank=True,
                        help_text="FIX P(signal), when the reviewer is FIX",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classifications",
                        to="core.component",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classifications",
                        to="core.reviewer",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("component", "reviewer"),
                        name="unique_rating_per_reviewer",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="component",
            constraint=models.UniqueConstraint(
                fields=("run", "index"), name="unique_component_per_run"
            ),
        ),
    )
